//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchPackage
    {
        public int BranchPackageID { get; set; }
        public int BranchID { get; set; }
        public int PackageID { get; set; }
        public System.DateTime DateStartZA { get; set; }
        public System.DateTime DateEndZA { get; set; }
        public byte PackageStatus { get; set; }
        public short Quantity { get; set; }
        public double Amount { get; set; }
        public int TransactionLogID { get; set; }
    }
}
