//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrowserAgent
    {
        public int BrowserAgentID { get; set; }
        public string BrowserAgentString { get; set; }
        public string FriendlyName { get; set; }
    }
}
