//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardStatistic
    {
        public int DashboardStatisticID { get; set; }
        public int AgencyID { get; set; }
        public int BranchID { get; set; }
        public System.DateTime DateStatistics { get; set; }
        public int NumPageViews { get; set; }
        public int NumPhoneClicks { get; set; }
        public int NumLeads { get; set; }
    }
}
