//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MXEntities : DbContext
    {
        public MXEntities()
            : base("name=MXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdTitleTemplate> AdTitleTemplates { get; set; }
        public virtual DbSet<Agency> Agencies { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<BranchPackage> BranchPackages { get; set; }
        public virtual DbSet<BranchUser> BranchUsers { get; set; }
        public virtual DbSet<DashboardStatistic> DashboardStatistics { get; set; }
        public virtual DbSet<DeletedProperty> DeletedProperties { get; set; }
        public virtual DbSet<GroupAdmin> GroupAdmins { get; set; }
        public virtual DbSet<GroupAgency> GroupAgencies { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<KeyValue> KeyValues { get; set; }
        public virtual DbSet<LeadDeliveryAddress> LeadDeliveryAddresses { get; set; }
        public virtual DbSet<Lead> Leads { get; set; }
        public virtual DbSet<LocalizationString> LocalizationStrings { get; set; }
        public virtual DbSet<LocationMapping> LocationMappings { get; set; }
        public virtual DbSet<OverlayPreference> OverlayPreferences { get; set; }
        public virtual DbSet<PhoneTracking> PhoneTrackings { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<PropertyAgent> PropertyAgents { get; set; }
        public virtual DbSet<PropertyExtentionInfo> PropertyExtentionInfoes { get; set; }
        public virtual DbSet<PropertyFeature> PropertyFeatures { get; set; }
        public virtual DbSet<PropertyPOIs> PropertyPOIs { get; set; }
        public virtual DbSet<PropertySubmit> PropertySubmits { get; set; }
        public virtual DbSet<SuperAdmin> SuperAdmins { get; set; }
        public virtual DbSet<SupportTicket> SupportTickets { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserBranch> UserBranches { get; set; }
        public virtual DbSet<UserExtensionInfo> UserExtensionInfos { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VivanunciosLocation> VivanunciosLocations { get; set; }
        public virtual DbSet<VivanunciosLocations2016_09_19> VivanunciosLocations2016_09_19 { get; set; }
        public virtual DbSet<VivanunciosMapping> VivanunciosMappings { get; set; }
        public virtual DbSet<VivanunciosPackage> VivanunciosPackages { get; set; }
        public virtual DbSet<x_OneTimePasswords> x_OneTimePasswords { get; set; }
    
        [DbFunction("MXEntities", "fn_int_list_to_table")]
        public virtual IQueryable<fn_int_list_to_table_Result> fn_int_list_to_table(string list)
        {
            var listParameter = list != null ?
                new ObjectParameter("list", list) :
                new ObjectParameter("list", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_int_list_to_table_Result>("[MXEntities].[fn_int_list_to_table](@list)", listParameter);
        }
    
        [DbFunction("MXEntities", "fnSplitString")]
        public virtual IQueryable<fnSplitString_Result> fnSplitString(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("string", @string) :
                new ObjectParameter("string", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("delimiter", delimiter) :
                new ObjectParameter("delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnSplitString_Result>("[MXEntities].[fnSplitString](@string, @delimiter)", stringParameter, delimiterParameter);
        }
    
        [DbFunction("MXEntities", "Split")]
        public virtual IQueryable<Split_Result> Split(string stringToSplit, string separator)
        {
            var stringToSplitParameter = stringToSplit != null ?
                new ObjectParameter("StringToSplit", stringToSplit) :
                new ObjectParameter("StringToSplit", typeof(string));
    
            var separatorParameter = separator != null ?
                new ObjectParameter("Separator", separator) :
                new ObjectParameter("Separator", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_Result>("[MXEntities].[Split](@StringToSplit, @Separator)", stringToSplitParameter, separatorParameter);
        }
    
        public virtual ObjectResult<BranchManager_GetSuperAdminBranchStats_Result> BranchManager_GetSuperAdminBranchStats(string statuses, Nullable<int> agencyID, string importFeed)
        {
            var statusesParameter = statuses != null ?
                new ObjectParameter("Statuses", statuses) :
                new ObjectParameter("Statuses", typeof(string));
    
            var agencyIDParameter = agencyID.HasValue ?
                new ObjectParameter("AgencyID", agencyID) :
                new ObjectParameter("AgencyID", typeof(int));
    
            var importFeedParameter = importFeed != null ?
                new ObjectParameter("ImportFeed", importFeed) :
                new ObjectParameter("ImportFeed", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BranchManager_GetSuperAdminBranchStats_Result>("BranchManager_GetSuperAdminBranchStats", statusesParameter, agencyIDParameter, importFeedParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Common_CountLiveAds(Nullable<int> agencyID, Nullable<int> branchID)
        {
            var agencyIDParameter = agencyID.HasValue ?
                new ObjectParameter("AgencyID", agencyID) :
                new ObjectParameter("AgencyID", typeof(int));
    
            var branchIDParameter = branchID.HasValue ?
                new ObjectParameter("BranchID", branchID) :
                new ObjectParameter("BranchID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Common_CountLiveAds", agencyIDParameter, branchIDParameter);
        }
    
        public virtual ObjectResult<Common_GetPropertyByPropertySubmitID_Result> Common_GetPropertyByPropertySubmitID(Nullable<int> propertySubmitID)
        {
            var propertySubmitIDParameter = propertySubmitID.HasValue ?
                new ObjectParameter("PropertySubmitID", propertySubmitID) :
                new ObjectParameter("PropertySubmitID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Common_GetPropertyByPropertySubmitID_Result>("Common_GetPropertyByPropertySubmitID", propertySubmitIDParameter);
        }
    
        public virtual int DashboardStatistics_IncreaseLead(Nullable<int> agencyID, Nullable<int> branchID, Nullable<System.DateTime> dateStatistics)
        {
            var agencyIDParameter = agencyID.HasValue ?
                new ObjectParameter("AgencyID", agencyID) :
                new ObjectParameter("AgencyID", typeof(int));
    
            var branchIDParameter = branchID.HasValue ?
                new ObjectParameter("BranchID", branchID) :
                new ObjectParameter("BranchID", typeof(int));
    
            var dateStatisticsParameter = dateStatistics.HasValue ?
                new ObjectParameter("DateStatistics", dateStatistics) :
                new ObjectParameter("DateStatistics", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DashboardStatistics_IncreaseLead", agencyIDParameter, branchIDParameter, dateStatisticsParameter);
        }
    
        public virtual int DashboardStatistics_IncreasePageViews(Nullable<int> agencyID, Nullable<int> branchID, Nullable<System.DateTime> dateStatistics, Nullable<int> pageViews)
        {
            var agencyIDParameter = agencyID.HasValue ?
                new ObjectParameter("AgencyID", agencyID) :
                new ObjectParameter("AgencyID", typeof(int));
    
            var branchIDParameter = branchID.HasValue ?
                new ObjectParameter("BranchID", branchID) :
                new ObjectParameter("BranchID", typeof(int));
    
            var dateStatisticsParameter = dateStatistics.HasValue ?
                new ObjectParameter("DateStatistics", dateStatistics) :
                new ObjectParameter("DateStatistics", typeof(System.DateTime));
    
            var pageViewsParameter = pageViews.HasValue ?
                new ObjectParameter("PageViews", pageViews) :
                new ObjectParameter("PageViews", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DashboardStatistics_IncreasePageViews", agencyIDParameter, branchIDParameter, dateStatisticsParameter, pageViewsParameter);
        }
    
        public virtual int DashboardStatistics_IncreasePhoneClicks(Nullable<int> agencyID, Nullable<int> branchID, Nullable<System.DateTime> dateStatistics, Nullable<int> phoneClicks)
        {
            var agencyIDParameter = agencyID.HasValue ?
                new ObjectParameter("AgencyID", agencyID) :
                new ObjectParameter("AgencyID", typeof(int));
    
            var branchIDParameter = branchID.HasValue ?
                new ObjectParameter("BranchID", branchID) :
                new ObjectParameter("BranchID", typeof(int));
    
            var dateStatisticsParameter = dateStatistics.HasValue ?
                new ObjectParameter("DateStatistics", dateStatistics) :
                new ObjectParameter("DateStatistics", typeof(System.DateTime));
    
            var phoneClicksParameter = phoneClicks.HasValue ?
                new ObjectParameter("PhoneClicks", phoneClicks) :
                new ObjectParameter("PhoneClicks", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DashboardStatistics_IncreasePhoneClicks", agencyIDParameter, branchIDParameter, dateStatisticsParameter, phoneClicksParameter);
        }
    
        public virtual ObjectResult<ExpiredAgency_GetActiveAds_Result> ExpiredAgency_GetActiveAds(Nullable<int> agencyID, Nullable<int> branchID, Nullable<int> maxRecords)
        {
            var agencyIDParameter = agencyID.HasValue ?
                new ObjectParameter("AgencyID", agencyID) :
                new ObjectParameter("AgencyID", typeof(int));
    
            var branchIDParameter = branchID.HasValue ?
                new ObjectParameter("BranchID", branchID) :
                new ObjectParameter("BranchID", typeof(int));
    
            var maxRecordsParameter = maxRecords.HasValue ?
                new ObjectParameter("MaxRecords", maxRecords) :
                new ObjectParameter("MaxRecords", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExpiredAgency_GetActiveAds_Result>("ExpiredAgency_GetActiveAds", agencyIDParameter, branchIDParameter, maxRecordsParameter);
        }
    
        public virtual ObjectResult<ExpiredAgency_GetActiveBranchesWithMaxAds_Result> ExpiredAgency_GetActiveBranchesWithMaxAds()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExpiredAgency_GetActiveBranchesWithMaxAds_Result>("ExpiredAgency_GetActiveBranchesWithMaxAds");
        }
    
        public virtual ObjectResult<ExpiredAgency_GetExpiredBranches_Result> ExpiredAgency_GetExpiredBranches(Nullable<System.DateTime> dateNow)
        {
            var dateNowParameter = dateNow.HasValue ?
                new ObjectParameter("DateNow", dateNow) :
                new ObjectParameter("DateNow", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExpiredAgency_GetExpiredBranches_Result>("ExpiredAgency_GetExpiredBranches", dateNowParameter);
        }
    
        public virtual ObjectResult<ExpiredAgency_GetExpiredFeatureAds_Result> ExpiredAgency_GetExpiredFeatureAds(Nullable<System.DateTime> dateNow)
        {
            var dateNowParameter = dateNow.HasValue ?
                new ObjectParameter("DateNow", dateNow) :
                new ObjectParameter("DateNow", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExpiredAgency_GetExpiredFeatureAds_Result>("ExpiredAgency_GetExpiredFeatureAds", dateNowParameter);
        }
    
        public virtual ObjectResult<GetActiveBranchesForPostingReport_Result> GetActiveBranchesForPostingReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActiveBranchesForPostingReport_Result>("GetActiveBranchesForPostingReport");
        }
    
        public virtual ObjectResult<GetActiveBranchesForPostingReport2_Result> GetActiveBranchesForPostingReport2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActiveBranchesForPostingReport2_Result>("GetActiveBranchesForPostingReport2");
        }
    
        public virtual ObjectResult<GetActiveBranchesForPostingReportGA_Result> GetActiveBranchesForPostingReportGA(Nullable<int> groupID)
        {
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActiveBranchesForPostingReportGA_Result>("GetActiveBranchesForPostingReportGA", groupIDParameter);
        }
    
        public virtual ObjectResult<GetActiveBranchesForPostingReportGA2_Result> GetActiveBranchesForPostingReportGA2(Nullable<int> groupID)
        {
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActiveBranchesForPostingReportGA2_Result>("GetActiveBranchesForPostingReportGA2", groupIDParameter);
        }
    
        public virtual ObjectResult<GetCityProvinceFromPostalCode_Result> GetCityProvinceFromPostalCode(string postalCode)
        {
            var postalCodeParameter = postalCode != null ?
                new ObjectParameter("PostalCode", postalCode) :
                new ObjectParameter("PostalCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCityProvinceFromPostalCode_Result>("GetCityProvinceFromPostalCode", postalCodeParameter);
        }
    
        public virtual ObjectResult<GetLocationPostingReport_Result> GetLocationPostingReport(Nullable<System.DateTime> zAStart, Nullable<System.DateTime> zAEnd, Nullable<System.DateTime> utcStart, Nullable<System.DateTime> utcEnd, string branchStatus)
        {
            var zAStartParameter = zAStart.HasValue ?
                new ObjectParameter("ZAStart", zAStart) :
                new ObjectParameter("ZAStart", typeof(System.DateTime));
    
            var zAEndParameter = zAEnd.HasValue ?
                new ObjectParameter("ZAEnd", zAEnd) :
                new ObjectParameter("ZAEnd", typeof(System.DateTime));
    
            var utcStartParameter = utcStart.HasValue ?
                new ObjectParameter("UtcStart", utcStart) :
                new ObjectParameter("UtcStart", typeof(System.DateTime));
    
            var utcEndParameter = utcEnd.HasValue ?
                new ObjectParameter("UtcEnd", utcEnd) :
                new ObjectParameter("UtcEnd", typeof(System.DateTime));
    
            var branchStatusParameter = branchStatus != null ?
                new ObjectParameter("BranchStatus", branchStatus) :
                new ObjectParameter("BranchStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLocationPostingReport_Result>("GetLocationPostingReport", zAStartParameter, zAEndParameter, utcStartParameter, utcEndParameter, branchStatusParameter);
        }
    
        public virtual ObjectResult<GetLocationPostingReport2_Result> GetLocationPostingReport2(Nullable<System.DateTime> zAStart, Nullable<System.DateTime> zAEnd, Nullable<System.DateTime> utcStart, Nullable<System.DateTime> utcEnd, string branchStatus, string branchPrefixFilter)
        {
            var zAStartParameter = zAStart.HasValue ?
                new ObjectParameter("ZAStart", zAStart) :
                new ObjectParameter("ZAStart", typeof(System.DateTime));
    
            var zAEndParameter = zAEnd.HasValue ?
                new ObjectParameter("ZAEnd", zAEnd) :
                new ObjectParameter("ZAEnd", typeof(System.DateTime));
    
            var utcStartParameter = utcStart.HasValue ?
                new ObjectParameter("UtcStart", utcStart) :
                new ObjectParameter("UtcStart", typeof(System.DateTime));
    
            var utcEndParameter = utcEnd.HasValue ?
                new ObjectParameter("UtcEnd", utcEnd) :
                new ObjectParameter("UtcEnd", typeof(System.DateTime));
    
            var branchStatusParameter = branchStatus != null ?
                new ObjectParameter("BranchStatus", branchStatus) :
                new ObjectParameter("BranchStatus", typeof(string));
    
            var branchPrefixFilterParameter = branchPrefixFilter != null ?
                new ObjectParameter("BranchPrefixFilter", branchPrefixFilter) :
                new ObjectParameter("BranchPrefixFilter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLocationPostingReport2_Result>("GetLocationPostingReport2", zAStartParameter, zAEndParameter, utcStartParameter, utcEndParameter, branchStatusParameter, branchPrefixFilterParameter);
        }
    
        public virtual ObjectResult<GetLocationPostingReportForGroupAgency_Result> GetLocationPostingReportForGroupAgency(Nullable<System.DateTime> zAStart, Nullable<System.DateTime> zAEnd, Nullable<System.DateTime> utcStart, Nullable<System.DateTime> utcEnd, Nullable<int> groupID, string branchStatus)
        {
            var zAStartParameter = zAStart.HasValue ?
                new ObjectParameter("ZAStart", zAStart) :
                new ObjectParameter("ZAStart", typeof(System.DateTime));
    
            var zAEndParameter = zAEnd.HasValue ?
                new ObjectParameter("ZAEnd", zAEnd) :
                new ObjectParameter("ZAEnd", typeof(System.DateTime));
    
            var utcStartParameter = utcStart.HasValue ?
                new ObjectParameter("UtcStart", utcStart) :
                new ObjectParameter("UtcStart", typeof(System.DateTime));
    
            var utcEndParameter = utcEnd.HasValue ?
                new ObjectParameter("UtcEnd", utcEnd) :
                new ObjectParameter("UtcEnd", typeof(System.DateTime));
    
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            var branchStatusParameter = branchStatus != null ?
                new ObjectParameter("BranchStatus", branchStatus) :
                new ObjectParameter("BranchStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLocationPostingReportForGroupAgency_Result>("GetLocationPostingReportForGroupAgency", zAStartParameter, zAEndParameter, utcStartParameter, utcEndParameter, groupIDParameter, branchStatusParameter);
        }
    
        public virtual ObjectResult<GetLocationPostingReportForGroupAgency2_Result> GetLocationPostingReportForGroupAgency2(Nullable<System.DateTime> zAStart, Nullable<System.DateTime> zAEnd, Nullable<System.DateTime> utcStart, Nullable<System.DateTime> utcEnd, Nullable<int> groupID, string branchStatus, string branchPrefixFilter)
        {
            var zAStartParameter = zAStart.HasValue ?
                new ObjectParameter("ZAStart", zAStart) :
                new ObjectParameter("ZAStart", typeof(System.DateTime));
    
            var zAEndParameter = zAEnd.HasValue ?
                new ObjectParameter("ZAEnd", zAEnd) :
                new ObjectParameter("ZAEnd", typeof(System.DateTime));
    
            var utcStartParameter = utcStart.HasValue ?
                new ObjectParameter("UtcStart", utcStart) :
                new ObjectParameter("UtcStart", typeof(System.DateTime));
    
            var utcEndParameter = utcEnd.HasValue ?
                new ObjectParameter("UtcEnd", utcEnd) :
                new ObjectParameter("UtcEnd", typeof(System.DateTime));
    
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            var branchStatusParameter = branchStatus != null ?
                new ObjectParameter("BranchStatus", branchStatus) :
                new ObjectParameter("BranchStatus", typeof(string));
    
            var branchPrefixFilterParameter = branchPrefixFilter != null ?
                new ObjectParameter("BranchPrefixFilter", branchPrefixFilter) :
                new ObjectParameter("BranchPrefixFilter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLocationPostingReportForGroupAgency2_Result>("GetLocationPostingReportForGroupAgency2", zAStartParameter, zAEndParameter, utcStartParameter, utcEndParameter, groupIDParameter, branchStatusParameter, branchPrefixFilterParameter);
        }
    
        public virtual ObjectResult<GetPostingReportDetailData_Result> GetPostingReportDetailData(Nullable<System.DateTime> zAStart, Nullable<System.DateTime> zAEnd, Nullable<System.DateTime> utcStart, Nullable<System.DateTime> utcEnd, string branchStatus)
        {
            var zAStartParameter = zAStart.HasValue ?
                new ObjectParameter("ZAStart", zAStart) :
                new ObjectParameter("ZAStart", typeof(System.DateTime));
    
            var zAEndParameter = zAEnd.HasValue ?
                new ObjectParameter("ZAEnd", zAEnd) :
                new ObjectParameter("ZAEnd", typeof(System.DateTime));
    
            var utcStartParameter = utcStart.HasValue ?
                new ObjectParameter("UtcStart", utcStart) :
                new ObjectParameter("UtcStart", typeof(System.DateTime));
    
            var utcEndParameter = utcEnd.HasValue ?
                new ObjectParameter("UtcEnd", utcEnd) :
                new ObjectParameter("UtcEnd", typeof(System.DateTime));
    
            var branchStatusParameter = branchStatus != null ?
                new ObjectParameter("BranchStatus", branchStatus) :
                new ObjectParameter("BranchStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPostingReportDetailData_Result>("GetPostingReportDetailData", zAStartParameter, zAEndParameter, utcStartParameter, utcEndParameter, branchStatusParameter);
        }
    
        public virtual ObjectResult<GetPostingReportDetailDataForGroupAgency_Result> GetPostingReportDetailDataForGroupAgency(Nullable<System.DateTime> zAStart, Nullable<System.DateTime> zAEnd, Nullable<System.DateTime> utcStart, Nullable<System.DateTime> utcEnd, Nullable<int> groupID, string branchStatus)
        {
            var zAStartParameter = zAStart.HasValue ?
                new ObjectParameter("ZAStart", zAStart) :
                new ObjectParameter("ZAStart", typeof(System.DateTime));
    
            var zAEndParameter = zAEnd.HasValue ?
                new ObjectParameter("ZAEnd", zAEnd) :
                new ObjectParameter("ZAEnd", typeof(System.DateTime));
    
            var utcStartParameter = utcStart.HasValue ?
                new ObjectParameter("UtcStart", utcStart) :
                new ObjectParameter("UtcStart", typeof(System.DateTime));
    
            var utcEndParameter = utcEnd.HasValue ?
                new ObjectParameter("UtcEnd", utcEnd) :
                new ObjectParameter("UtcEnd", typeof(System.DateTime));
    
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            var branchStatusParameter = branchStatus != null ?
                new ObjectParameter("BranchStatus", branchStatus) :
                new ObjectParameter("BranchStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPostingReportDetailDataForGroupAgency_Result>("GetPostingReportDetailDataForGroupAgency", zAStartParameter, zAEndParameter, utcStartParameter, utcEndParameter, groupIDParameter, branchStatusParameter);
        }
    
        public virtual ObjectResult<GetPropertyTypePostingReport_Result> GetPropertyTypePostingReport(Nullable<System.DateTime> zAStart, Nullable<System.DateTime> zAEnd, Nullable<System.DateTime> utcStart, Nullable<System.DateTime> utcEnd, string branchStatus)
        {
            var zAStartParameter = zAStart.HasValue ?
                new ObjectParameter("ZAStart", zAStart) :
                new ObjectParameter("ZAStart", typeof(System.DateTime));
    
            var zAEndParameter = zAEnd.HasValue ?
                new ObjectParameter("ZAEnd", zAEnd) :
                new ObjectParameter("ZAEnd", typeof(System.DateTime));
    
            var utcStartParameter = utcStart.HasValue ?
                new ObjectParameter("UtcStart", utcStart) :
                new ObjectParameter("UtcStart", typeof(System.DateTime));
    
            var utcEndParameter = utcEnd.HasValue ?
                new ObjectParameter("UtcEnd", utcEnd) :
                new ObjectParameter("UtcEnd", typeof(System.DateTime));
    
            var branchStatusParameter = branchStatus != null ?
                new ObjectParameter("BranchStatus", branchStatus) :
                new ObjectParameter("BranchStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPropertyTypePostingReport_Result>("GetPropertyTypePostingReport", zAStartParameter, zAEndParameter, utcStartParameter, utcEndParameter, branchStatusParameter);
        }
    
        public virtual ObjectResult<GetPropertyTypePostingReport2_Result> GetPropertyTypePostingReport2(Nullable<System.DateTime> zAStart, Nullable<System.DateTime> zAEnd, Nullable<System.DateTime> utcStart, Nullable<System.DateTime> utcEnd, string branchStatus, string branchPrefixFilter)
        {
            var zAStartParameter = zAStart.HasValue ?
                new ObjectParameter("ZAStart", zAStart) :
                new ObjectParameter("ZAStart", typeof(System.DateTime));
    
            var zAEndParameter = zAEnd.HasValue ?
                new ObjectParameter("ZAEnd", zAEnd) :
                new ObjectParameter("ZAEnd", typeof(System.DateTime));
    
            var utcStartParameter = utcStart.HasValue ?
                new ObjectParameter("UtcStart", utcStart) :
                new ObjectParameter("UtcStart", typeof(System.DateTime));
    
            var utcEndParameter = utcEnd.HasValue ?
                new ObjectParameter("UtcEnd", utcEnd) :
                new ObjectParameter("UtcEnd", typeof(System.DateTime));
    
            var branchStatusParameter = branchStatus != null ?
                new ObjectParameter("BranchStatus", branchStatus) :
                new ObjectParameter("BranchStatus", typeof(string));
    
            var branchPrefixFilterParameter = branchPrefixFilter != null ?
                new ObjectParameter("BranchPrefixFilter", branchPrefixFilter) :
                new ObjectParameter("BranchPrefixFilter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPropertyTypePostingReport2_Result>("GetPropertyTypePostingReport2", zAStartParameter, zAEndParameter, utcStartParameter, utcEndParameter, branchStatusParameter, branchPrefixFilterParameter);
        }
    
        public virtual ObjectResult<GetPropertyTypePostingReportForGroupAgency_Result> GetPropertyTypePostingReportForGroupAgency(Nullable<System.DateTime> zAStart, Nullable<System.DateTime> zAEnd, Nullable<System.DateTime> utcStart, Nullable<System.DateTime> utcEnd, Nullable<int> groupID, string branchStatus)
        {
            var zAStartParameter = zAStart.HasValue ?
                new ObjectParameter("ZAStart", zAStart) :
                new ObjectParameter("ZAStart", typeof(System.DateTime));
    
            var zAEndParameter = zAEnd.HasValue ?
                new ObjectParameter("ZAEnd", zAEnd) :
                new ObjectParameter("ZAEnd", typeof(System.DateTime));
    
            var utcStartParameter = utcStart.HasValue ?
                new ObjectParameter("UtcStart", utcStart) :
                new ObjectParameter("UtcStart", typeof(System.DateTime));
    
            var utcEndParameter = utcEnd.HasValue ?
                new ObjectParameter("UtcEnd", utcEnd) :
                new ObjectParameter("UtcEnd", typeof(System.DateTime));
    
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            var branchStatusParameter = branchStatus != null ?
                new ObjectParameter("BranchStatus", branchStatus) :
                new ObjectParameter("BranchStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPropertyTypePostingReportForGroupAgency_Result>("GetPropertyTypePostingReportForGroupAgency", zAStartParameter, zAEndParameter, utcStartParameter, utcEndParameter, groupIDParameter, branchStatusParameter);
        }
    
        public virtual ObjectResult<GetPropertyTypePostingReportForGroupAgency2_Result> GetPropertyTypePostingReportForGroupAgency2(Nullable<System.DateTime> zAStart, Nullable<System.DateTime> zAEnd, Nullable<System.DateTime> utcStart, Nullable<System.DateTime> utcEnd, Nullable<int> groupID, string branchStatus, string branchPrefixFilter)
        {
            var zAStartParameter = zAStart.HasValue ?
                new ObjectParameter("ZAStart", zAStart) :
                new ObjectParameter("ZAStart", typeof(System.DateTime));
    
            var zAEndParameter = zAEnd.HasValue ?
                new ObjectParameter("ZAEnd", zAEnd) :
                new ObjectParameter("ZAEnd", typeof(System.DateTime));
    
            var utcStartParameter = utcStart.HasValue ?
                new ObjectParameter("UtcStart", utcStart) :
                new ObjectParameter("UtcStart", typeof(System.DateTime));
    
            var utcEndParameter = utcEnd.HasValue ?
                new ObjectParameter("UtcEnd", utcEnd) :
                new ObjectParameter("UtcEnd", typeof(System.DateTime));
    
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            var branchStatusParameter = branchStatus != null ?
                new ObjectParameter("BranchStatus", branchStatus) :
                new ObjectParameter("BranchStatus", typeof(string));
    
            var branchPrefixFilterParameter = branchPrefixFilter != null ?
                new ObjectParameter("BranchPrefixFilter", branchPrefixFilter) :
                new ObjectParameter("BranchPrefixFilter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPropertyTypePostingReportForGroupAgency2_Result>("GetPropertyTypePostingReportForGroupAgency2", zAStartParameter, zAEndParameter, utcStartParameter, utcEndParameter, groupIDParameter, branchStatusParameter, branchPrefixFilterParameter);
        }
    
        public virtual int GetSystemBranchLeadReport(Nullable<System.DateTime> zAStart, Nullable<System.DateTime> zAEnd, Nullable<System.DateTime> utcStart, Nullable<System.DateTime> utcEnd, Nullable<int> agencyId, Nullable<int> groupId, string sortBy, string branchStatus, Nullable<bool> isBranchWithoutLead)
        {
            var zAStartParameter = zAStart.HasValue ?
                new ObjectParameter("ZAStart", zAStart) :
                new ObjectParameter("ZAStart", typeof(System.DateTime));
    
            var zAEndParameter = zAEnd.HasValue ?
                new ObjectParameter("ZAEnd", zAEnd) :
                new ObjectParameter("ZAEnd", typeof(System.DateTime));
    
            var utcStartParameter = utcStart.HasValue ?
                new ObjectParameter("UtcStart", utcStart) :
                new ObjectParameter("UtcStart", typeof(System.DateTime));
    
            var utcEndParameter = utcEnd.HasValue ?
                new ObjectParameter("UtcEnd", utcEnd) :
                new ObjectParameter("UtcEnd", typeof(System.DateTime));
    
            var agencyIdParameter = agencyId.HasValue ?
                new ObjectParameter("AgencyId", agencyId) :
                new ObjectParameter("AgencyId", typeof(int));
    
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var sortByParameter = sortBy != null ?
                new ObjectParameter("SortBy", sortBy) :
                new ObjectParameter("SortBy", typeof(string));
    
            var branchStatusParameter = branchStatus != null ?
                new ObjectParameter("BranchStatus", branchStatus) :
                new ObjectParameter("BranchStatus", typeof(string));
    
            var isBranchWithoutLeadParameter = isBranchWithoutLead.HasValue ?
                new ObjectParameter("IsBranchWithoutLead", isBranchWithoutLead) :
                new ObjectParameter("IsBranchWithoutLead", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetSystemBranchLeadReport", zAStartParameter, zAEndParameter, utcStartParameter, utcEndParameter, agencyIdParameter, groupIdParameter, sortByParameter, branchStatusParameter, isBranchWithoutLeadParameter);
        }
    
        public virtual int GetSystemBranchLeadReport2(Nullable<System.DateTime> zAStart, Nullable<System.DateTime> zAEnd, Nullable<System.DateTime> utcStart, Nullable<System.DateTime> utcEnd, Nullable<int> agencyId, Nullable<int> groupId, string sortBy, string branchStatus, Nullable<bool> isBranchWithoutLead)
        {
            var zAStartParameter = zAStart.HasValue ?
                new ObjectParameter("ZAStart", zAStart) :
                new ObjectParameter("ZAStart", typeof(System.DateTime));
    
            var zAEndParameter = zAEnd.HasValue ?
                new ObjectParameter("ZAEnd", zAEnd) :
                new ObjectParameter("ZAEnd", typeof(System.DateTime));
    
            var utcStartParameter = utcStart.HasValue ?
                new ObjectParameter("UtcStart", utcStart) :
                new ObjectParameter("UtcStart", typeof(System.DateTime));
    
            var utcEndParameter = utcEnd.HasValue ?
                new ObjectParameter("UtcEnd", utcEnd) :
                new ObjectParameter("UtcEnd", typeof(System.DateTime));
    
            var agencyIdParameter = agencyId.HasValue ?
                new ObjectParameter("AgencyId", agencyId) :
                new ObjectParameter("AgencyId", typeof(int));
    
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var sortByParameter = sortBy != null ?
                new ObjectParameter("SortBy", sortBy) :
                new ObjectParameter("SortBy", typeof(string));
    
            var branchStatusParameter = branchStatus != null ?
                new ObjectParameter("BranchStatus", branchStatus) :
                new ObjectParameter("BranchStatus", typeof(string));
    
            var isBranchWithoutLeadParameter = isBranchWithoutLead.HasValue ?
                new ObjectParameter("IsBranchWithoutLead", isBranchWithoutLead) :
                new ObjectParameter("IsBranchWithoutLead", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetSystemBranchLeadReport2", zAStartParameter, zAEndParameter, utcStartParameter, utcEndParameter, agencyIdParameter, groupIdParameter, sortByParameter, branchStatusParameter, isBranchWithoutLeadParameter);
        }
    
        public virtual ObjectResult<GetSystemLeadReport_Result> GetSystemLeadReport(Nullable<System.DateTime> zAStart, Nullable<System.DateTime> zAEnd, Nullable<System.DateTime> utcStart, Nullable<System.DateTime> utcEnd, Nullable<int> agencyId, Nullable<int> groupId, string branchStatus)
        {
            var zAStartParameter = zAStart.HasValue ?
                new ObjectParameter("ZAStart", zAStart) :
                new ObjectParameter("ZAStart", typeof(System.DateTime));
    
            var zAEndParameter = zAEnd.HasValue ?
                new ObjectParameter("ZAEnd", zAEnd) :
                new ObjectParameter("ZAEnd", typeof(System.DateTime));
    
            var utcStartParameter = utcStart.HasValue ?
                new ObjectParameter("UtcStart", utcStart) :
                new ObjectParameter("UtcStart", typeof(System.DateTime));
    
            var utcEndParameter = utcEnd.HasValue ?
                new ObjectParameter("UtcEnd", utcEnd) :
                new ObjectParameter("UtcEnd", typeof(System.DateTime));
    
            var agencyIdParameter = agencyId.HasValue ?
                new ObjectParameter("AgencyId", agencyId) :
                new ObjectParameter("AgencyId", typeof(int));
    
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var branchStatusParameter = branchStatus != null ?
                new ObjectParameter("BranchStatus", branchStatus) :
                new ObjectParameter("BranchStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSystemLeadReport_Result>("GetSystemLeadReport", zAStartParameter, zAEndParameter, utcStartParameter, utcEndParameter, agencyIdParameter, groupIdParameter, branchStatusParameter);
        }
    
        public virtual ObjectResult<GetSystemLeadReport2_Result> GetSystemLeadReport2(Nullable<System.DateTime> zAStart, Nullable<System.DateTime> zAEnd, Nullable<System.DateTime> utcStart, Nullable<System.DateTime> utcEnd, Nullable<int> agencyId, Nullable<int> groupId, string branchStatus)
        {
            var zAStartParameter = zAStart.HasValue ?
                new ObjectParameter("ZAStart", zAStart) :
                new ObjectParameter("ZAStart", typeof(System.DateTime));
    
            var zAEndParameter = zAEnd.HasValue ?
                new ObjectParameter("ZAEnd", zAEnd) :
                new ObjectParameter("ZAEnd", typeof(System.DateTime));
    
            var utcStartParameter = utcStart.HasValue ?
                new ObjectParameter("UtcStart", utcStart) :
                new ObjectParameter("UtcStart", typeof(System.DateTime));
    
            var utcEndParameter = utcEnd.HasValue ?
                new ObjectParameter("UtcEnd", utcEnd) :
                new ObjectParameter("UtcEnd", typeof(System.DateTime));
    
            var agencyIdParameter = agencyId.HasValue ?
                new ObjectParameter("AgencyId", agencyId) :
                new ObjectParameter("AgencyId", typeof(int));
    
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var branchStatusParameter = branchStatus != null ?
                new ObjectParameter("BranchStatus", branchStatus) :
                new ObjectParameter("BranchStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSystemLeadReport2_Result>("GetSystemLeadReport2", zAStartParameter, zAEndParameter, utcStartParameter, utcEndParameter, agencyIdParameter, groupIdParameter, branchStatusParameter);
        }
    
        public virtual int GetSystemPostingReport(Nullable<System.DateTime> zAStart, Nullable<System.DateTime> zAEnd, Nullable<System.DateTime> utcStart, Nullable<System.DateTime> utcEnd, string branchStatus)
        {
            var zAStartParameter = zAStart.HasValue ?
                new ObjectParameter("ZAStart", zAStart) :
                new ObjectParameter("ZAStart", typeof(System.DateTime));
    
            var zAEndParameter = zAEnd.HasValue ?
                new ObjectParameter("ZAEnd", zAEnd) :
                new ObjectParameter("ZAEnd", typeof(System.DateTime));
    
            var utcStartParameter = utcStart.HasValue ?
                new ObjectParameter("UtcStart", utcStart) :
                new ObjectParameter("UtcStart", typeof(System.DateTime));
    
            var utcEndParameter = utcEnd.HasValue ?
                new ObjectParameter("UtcEnd", utcEnd) :
                new ObjectParameter("UtcEnd", typeof(System.DateTime));
    
            var branchStatusParameter = branchStatus != null ?
                new ObjectParameter("BranchStatus", branchStatus) :
                new ObjectParameter("BranchStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetSystemPostingReport", zAStartParameter, zAEndParameter, utcStartParameter, utcEndParameter, branchStatusParameter);
        }
    
        public virtual ObjectResult<GetSystemPostingReport2_Result> GetSystemPostingReport2(Nullable<System.DateTime> zAStart, Nullable<System.DateTime> zAEnd, Nullable<System.DateTime> utcStart, Nullable<System.DateTime> utcEnd, string branchStatus, string branchPrefixFilter)
        {
            var zAStartParameter = zAStart.HasValue ?
                new ObjectParameter("ZAStart", zAStart) :
                new ObjectParameter("ZAStart", typeof(System.DateTime));
    
            var zAEndParameter = zAEnd.HasValue ?
                new ObjectParameter("ZAEnd", zAEnd) :
                new ObjectParameter("ZAEnd", typeof(System.DateTime));
    
            var utcStartParameter = utcStart.HasValue ?
                new ObjectParameter("UtcStart", utcStart) :
                new ObjectParameter("UtcStart", typeof(System.DateTime));
    
            var utcEndParameter = utcEnd.HasValue ?
                new ObjectParameter("UtcEnd", utcEnd) :
                new ObjectParameter("UtcEnd", typeof(System.DateTime));
    
            var branchStatusParameter = branchStatus != null ?
                new ObjectParameter("BranchStatus", branchStatus) :
                new ObjectParameter("BranchStatus", typeof(string));
    
            var branchPrefixFilterParameter = branchPrefixFilter != null ?
                new ObjectParameter("BranchPrefixFilter", branchPrefixFilter) :
                new ObjectParameter("BranchPrefixFilter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSystemPostingReport2_Result>("GetSystemPostingReport2", zAStartParameter, zAEndParameter, utcStartParameter, utcEndParameter, branchStatusParameter, branchPrefixFilterParameter);
        }
    
        public virtual ObjectResult<GetSystemPostingReportForGroupAgency_Result> GetSystemPostingReportForGroupAgency(Nullable<System.DateTime> zAStart, Nullable<System.DateTime> zAEnd, Nullable<System.DateTime> utcStart, Nullable<System.DateTime> utcEnd, Nullable<int> groupID, string branchStatus)
        {
            var zAStartParameter = zAStart.HasValue ?
                new ObjectParameter("ZAStart", zAStart) :
                new ObjectParameter("ZAStart", typeof(System.DateTime));
    
            var zAEndParameter = zAEnd.HasValue ?
                new ObjectParameter("ZAEnd", zAEnd) :
                new ObjectParameter("ZAEnd", typeof(System.DateTime));
    
            var utcStartParameter = utcStart.HasValue ?
                new ObjectParameter("UtcStart", utcStart) :
                new ObjectParameter("UtcStart", typeof(System.DateTime));
    
            var utcEndParameter = utcEnd.HasValue ?
                new ObjectParameter("UtcEnd", utcEnd) :
                new ObjectParameter("UtcEnd", typeof(System.DateTime));
    
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            var branchStatusParameter = branchStatus != null ?
                new ObjectParameter("BranchStatus", branchStatus) :
                new ObjectParameter("BranchStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSystemPostingReportForGroupAgency_Result>("GetSystemPostingReportForGroupAgency", zAStartParameter, zAEndParameter, utcStartParameter, utcEndParameter, groupIDParameter, branchStatusParameter);
        }
    
        public virtual ObjectResult<GetSystemPostingReportForGroupAgency2_Result> GetSystemPostingReportForGroupAgency2(Nullable<System.DateTime> zAStart, Nullable<System.DateTime> zAEnd, Nullable<System.DateTime> utcStart, Nullable<System.DateTime> utcEnd, Nullable<int> groupID, string branchStatus, string branchPrefixFilter)
        {
            var zAStartParameter = zAStart.HasValue ?
                new ObjectParameter("ZAStart", zAStart) :
                new ObjectParameter("ZAStart", typeof(System.DateTime));
    
            var zAEndParameter = zAEnd.HasValue ?
                new ObjectParameter("ZAEnd", zAEnd) :
                new ObjectParameter("ZAEnd", typeof(System.DateTime));
    
            var utcStartParameter = utcStart.HasValue ?
                new ObjectParameter("UtcStart", utcStart) :
                new ObjectParameter("UtcStart", typeof(System.DateTime));
    
            var utcEndParameter = utcEnd.HasValue ?
                new ObjectParameter("UtcEnd", utcEnd) :
                new ObjectParameter("UtcEnd", typeof(System.DateTime));
    
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            var branchStatusParameter = branchStatus != null ?
                new ObjectParameter("BranchStatus", branchStatus) :
                new ObjectParameter("BranchStatus", typeof(string));
    
            var branchPrefixFilterParameter = branchPrefixFilter != null ?
                new ObjectParameter("BranchPrefixFilter", branchPrefixFilter) :
                new ObjectParameter("BranchPrefixFilter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSystemPostingReportForGroupAgency2_Result>("GetSystemPostingReportForGroupAgency2", zAStartParameter, zAEndParameter, utcStartParameter, utcEndParameter, groupIDParameter, branchStatusParameter, branchPrefixFilterParameter);
        }
    
        public virtual ObjectResult<GetUnassignedUsers_Result> GetUnassignedUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUnassignedUsers_Result>("GetUnassignedUsers");
        }
    
        public virtual ObjectResult<HealthCheck_GetStats_Result> HealthCheck_GetStats()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HealthCheck_GetStats_Result>("HealthCheck_GetStats");
        }
    
        public virtual ObjectResult<ImageDownloader_GetPropertySubmitsToDownload_Result> ImageDownloader_GetPropertySubmitsToDownload(Nullable<int> maxRecords)
        {
            var maxRecordsParameter = maxRecords.HasValue ?
                new ObjectParameter("MaxRecords", maxRecords) :
                new ObjectParameter("MaxRecords", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ImageDownloader_GetPropertySubmitsToDownload_Result>("ImageDownloader_GetPropertySubmitsToDownload", maxRecordsParameter);
        }
    
        public virtual ObjectResult<LocationParser_GetActiveBranches_Result> LocationParser_GetActiveBranches()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LocationParser_GetActiveBranches_Result>("LocationParser_GetActiveBranches");
        }
    
        public virtual ObjectResult<LocationParser_GetNextPropertySubmitWithoutLocation_Result> LocationParser_GetNextPropertySubmitWithoutLocation(Nullable<int> agencyID, Nullable<int> branchID)
        {
            var agencyIDParameter = agencyID.HasValue ?
                new ObjectParameter("AgencyID", agencyID) :
                new ObjectParameter("AgencyID", typeof(int));
    
            var branchIDParameter = branchID.HasValue ?
                new ObjectParameter("BranchID", branchID) :
                new ObjectParameter("BranchID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LocationParser_GetNextPropertySubmitWithoutLocation_Result>("LocationParser_GetNextPropertySubmitWithoutLocation", agencyIDParameter, branchIDParameter);
        }
    
        public virtual ObjectResult<LocationParser_GetPropertySubmits_Result> LocationParser_GetPropertySubmits()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LocationParser_GetPropertySubmits_Result>("LocationParser_GetPropertySubmits");
        }
    
        public virtual ObjectResult<NotifyEngine_GetAccountsWithoutPackages_Result> NotifyEngine_GetAccountsWithoutPackages(Nullable<System.DateTime> dateLimited)
        {
            var dateLimitedParameter = dateLimited.HasValue ?
                new ObjectParameter("DateLimited", dateLimited) :
                new ObjectParameter("DateLimited", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NotifyEngine_GetAccountsWithoutPackages_Result>("NotifyEngine_GetAccountsWithoutPackages", dateLimitedParameter);
        }
    
        public virtual int PhoneTracking_ForceToUpdatePropertySubmits(Nullable<int> branchID, Nullable<int> userID)
        {
            var branchIDParameter = branchID.HasValue ?
                new ObjectParameter("BranchID", branchID) :
                new ObjectParameter("BranchID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PhoneTracking_ForceToUpdatePropertySubmits", branchIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<PostEngine_GetActiveBranches_Result> PostEngine_GetActiveBranches(Nullable<System.DateTime> dateLimited)
        {
            var dateLimitedParameter = dateLimited.HasValue ?
                new ObjectParameter("DateLimited", dateLimited) :
                new ObjectParameter("DateLimited", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PostEngine_GetActiveBranches_Result>("PostEngine_GetActiveBranches", dateLimitedParameter);
        }
    
        public virtual ObjectResult<PostEngine_GetCancelledPropertySubmits_Result> PostEngine_GetCancelledPropertySubmits(Nullable<int> maxREcords, Nullable<System.DateTime> dateNow)
        {
            var maxREcordsParameter = maxREcords.HasValue ?
                new ObjectParameter("MaxREcords", maxREcords) :
                new ObjectParameter("MaxREcords", typeof(int));
    
            var dateNowParameter = dateNow.HasValue ?
                new ObjectParameter("DateNow", dateNow) :
                new ObjectParameter("DateNow", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PostEngine_GetCancelledPropertySubmits_Result>("PostEngine_GetCancelledPropertySubmits", maxREcordsParameter, dateNowParameter);
        }
    
        public virtual ObjectResult<PostEngine_GetInactivePropertySubmits_Result> PostEngine_GetInactivePropertySubmits(Nullable<int> maxRecords)
        {
            var maxRecordsParameter = maxRecords.HasValue ?
                new ObjectParameter("MaxRecords", maxRecords) :
                new ObjectParameter("MaxRecords", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PostEngine_GetInactivePropertySubmits_Result>("PostEngine_GetInactivePropertySubmits", maxRecordsParameter);
        }
    
        public virtual ObjectResult<PostEngine_GetNextPropertySubmitToPost_Result> PostEngine_GetNextPropertySubmitToPost(Nullable<int> agencyID, Nullable<int> branchID, Nullable<System.DateTime> dateLimited)
        {
            var agencyIDParameter = agencyID.HasValue ?
                new ObjectParameter("AgencyID", agencyID) :
                new ObjectParameter("AgencyID", typeof(int));
    
            var branchIDParameter = branchID.HasValue ?
                new ObjectParameter("BranchID", branchID) :
                new ObjectParameter("BranchID", typeof(int));
    
            var dateLimitedParameter = dateLimited.HasValue ?
                new ObjectParameter("DateLimited", dateLimited) :
                new ObjectParameter("DateLimited", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PostEngine_GetNextPropertySubmitToPost_Result>("PostEngine_GetNextPropertySubmitToPost", agencyIDParameter, branchIDParameter, dateLimitedParameter);
        }
    
        public virtual ObjectResult<PostEngine_GetPropertySubmitsToRepost_Result> PostEngine_GetPropertySubmitsToRepost(Nullable<int> maxRecords, Nullable<System.DateTime> dateThreshold)
        {
            var maxRecordsParameter = maxRecords.HasValue ?
                new ObjectParameter("MaxRecords", maxRecords) :
                new ObjectParameter("MaxRecords", typeof(int));
    
            var dateThresholdParameter = dateThreshold.HasValue ?
                new ObjectParameter("DateThreshold", dateThreshold) :
                new ObjectParameter("DateThreshold", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PostEngine_GetPropertySubmitsToRepost_Result>("PostEngine_GetPropertySubmitsToRepost", maxRecordsParameter, dateThresholdParameter);
        }
    
        public virtual ObjectResult<PostEngine_GetPropertySubmitsToUpdate_Result> PostEngine_GetPropertySubmitsToUpdate(Nullable<int> maxRecords)
        {
            var maxRecordsParameter = maxRecords.HasValue ?
                new ObjectParameter("MaxRecords", maxRecords) :
                new ObjectParameter("MaxRecords", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PostEngine_GetPropertySubmitsToUpdate_Result>("PostEngine_GetPropertySubmitsToUpdate", maxRecordsParameter);
        }
    
        public virtual ObjectResult<ScheduleBumpUp_GetNextPendingBumpUp_Result> ScheduleBumpUp_GetNextPendingBumpUp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ScheduleBumpUp_GetNextPendingBumpUp_Result>("ScheduleBumpUp_GetNextPendingBumpUp");
        }
    
        public virtual int sp_AddNewLocalizationString(string field, string engValue, string spaValue, string screen)
        {
            var fieldParameter = field != null ?
                new ObjectParameter("Field", field) :
                new ObjectParameter("Field", typeof(string));
    
            var engValueParameter = engValue != null ?
                new ObjectParameter("EngValue", engValue) :
                new ObjectParameter("EngValue", typeof(string));
    
            var spaValueParameter = spaValue != null ?
                new ObjectParameter("SpaValue", spaValue) :
                new ObjectParameter("SpaValue", typeof(string));
    
            var screenParameter = screen != null ?
                new ObjectParameter("Screen", screen) :
                new ObjectParameter("Screen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddNewLocalizationString", fieldParameter, engValueParameter, spaValueParameter, screenParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<StatusPolling_GetActiveBranches_Result> StatusPolling_GetActiveBranches()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StatusPolling_GetActiveBranches_Result>("StatusPolling_GetActiveBranches");
        }
    
        public virtual ObjectResult<StatusPolling_GetAllActivePropertySubmits_Result> StatusPolling_GetAllActivePropertySubmits()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StatusPolling_GetAllActivePropertySubmits_Result>("StatusPolling_GetAllActivePropertySubmits");
        }
    
        public virtual ObjectResult<StatusPolling_GetAllPropertySubmitsWithoutAdUrl_Result> StatusPolling_GetAllPropertySubmitsWithoutAdUrl()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StatusPolling_GetAllPropertySubmitsWithoutAdUrl_Result>("StatusPolling_GetAllPropertySubmitsWithoutAdUrl");
        }
    
        public virtual ObjectResult<StatusPolling_GetPropertySubmitByAdID_Result> StatusPolling_GetPropertySubmitByAdID(string adID)
        {
            var adIDParameter = adID != null ?
                new ObjectParameter("AdID", adID) :
                new ObjectParameter("AdID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StatusPolling_GetPropertySubmitByAdID_Result>("StatusPolling_GetPropertySubmitByAdID", adIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SystemHealth_CountLastProceededLeads(Nullable<System.DateTime> dateStart, Nullable<byte> leadType)
        {
            var dateStartParameter = dateStart.HasValue ?
                new ObjectParameter("DateStart", dateStart) :
                new ObjectParameter("DateStart", typeof(System.DateTime));
    
            var leadTypeParameter = leadType.HasValue ?
                new ObjectParameter("LeadType", leadType) :
                new ObjectParameter("LeadType", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SystemHealth_CountLastProceededLeads", dateStartParameter, leadTypeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SystemHealth_CountPendingBumpUpAds()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SystemHealth_CountPendingBumpUpAds");
        }
    
        public virtual ObjectResult<Nullable<int>> SystemHealth_CountPendingCreateAds()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SystemHealth_CountPendingCreateAds");
        }
    
        public virtual ObjectResult<Nullable<int>> SystemHealth_CountPendingUpdateAds()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SystemHealth_CountPendingUpdateAds");
        }
    
        public virtual ObjectResult<SystemHealth_GetLeadDailyReport_Result> SystemHealth_GetLeadDailyReport(Nullable<System.DateTime> dateStart)
        {
            var dateStartParameter = dateStart.HasValue ?
                new ObjectParameter("DateStart", dateStart) :
                new ObjectParameter("DateStart", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SystemHealth_GetLeadDailyReport_Result>("SystemHealth_GetLeadDailyReport", dateStartParameter);
        }
    
        public virtual ObjectResult<SystemHealth_GetLeadHourlyReport_Result> SystemHealth_GetLeadHourlyReport(Nullable<System.DateTime> dateStart)
        {
            var dateStartParameter = dateStart.HasValue ?
                new ObjectParameter("DateStart", dateStart) :
                new ObjectParameter("DateStart", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SystemHealth_GetLeadHourlyReport_Result>("SystemHealth_GetLeadHourlyReport", dateStartParameter);
        }
    }
}
