//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedProperty
    {
        public int DeletedPropertyID { get; set; }
        public int AgencyID { get; set; }
        public int BranchID { get; set; }
        public int PropertyID { get; set; }
        public int DeletedBy { get; set; }
        public System.DateTime DateDeleted { get; set; }
    }
}
