//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public long ImageID { get; set; }
        public int ObjectID { get; set; }
        public string S3ID { get; set; }
        public string URL { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string FileName { get; set; }
        public byte ObjectType { get; set; }
        public byte ImageIndex { get; set; }
        public bool IsDeleted { get; set; }
    }
}
