//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        public int LeadID { get; set; }
        public int BranchID { get; set; }
        public int PropertyID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string URLReferrer { get; set; }
        public byte LeadStatus { get; set; }
        public string LeadSource { get; set; }
        public byte LeadType { get; set; }
        public Nullable<System.DateTime> DateDelivery { get; set; }
        public int AgencyUserID { get; set; }
        public int PhoneTrackingID { get; set; }
        public string ExternalID { get; set; }
        public string CallStatus { get; set; }
        public int CallDuration { get; set; }
    }
}
