//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadDeliveryAddress
    {
        public int LeadDeliveryAddressID { get; set; }
        public int AgencyID { get; set; }
        public int BranchID { get; set; }
        public string LeadType { get; set; }
        public string LeadAddress { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public int UpdatedBy { get; set; }
    }
}
