//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationMapping
    {
        public int LocationMappingID { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Neighborhood { get; set; }
        public int LocationID { get; set; }
    }
}
