//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalizationString
    {
        public int LocalizationStringID { get; set; }
        public string Language { get; set; }
        public string Field { get; set; }
        public string Value { get; set; }
        public string Screen { get; set; }
    }
}
