//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OneTimePassword
    {
        public int OneTimePasswordID { get; set; }
        public int UserID { get; set; }
        public System.Guid OTPKey { get; set; }
        public byte ExpirationHours { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateFirstLogin { get; set; }
        public int CreatedBy { get; set; }
    }
}
