//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverlayPreference
    {
        public int OverlayPreferenceID { get; set; }
        public int BranchID { get; set; }
        public string OverlayName { get; set; }
        public string OverlayFileName { get; set; }
        public bool IsActive { get; set; }
        public int ListingType { get; set; }
        public bool IsApplyAll { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public Nullable<bool> NeedsUpdateImage { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
