//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneTracking
    {
        public int PhoneTrackingID { get; set; }
        public int BranchID { get; set; }
        public string ForwardFromNumber { get; set; }
        public string ForwardToNumber { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public byte PhoneTrackingStatus { get; set; }
        public string PhoneFeatures { get; set; }
        public byte PhoneTrackingType { get; set; }
        public int AgencyUserID { get; set; }
    }
}
