//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyExtentionInfo
    {
        public int PropertyExtensionInfoID { get; set; }
        public int PropertyID { get; set; }
        public bool IsImportBlockedListingType { get; set; }
        public bool IsImportBlockedPropertyType { get; set; }
        public bool IsImportBlockedListingPrice { get; set; }
        public bool IsImportBlockedLevies { get; set; }
        public bool IsImportBlockedRatesAndTaxes { get; set; }
        public bool IsImportBlockedAddress { get; set; }
        public bool IsImportBlockedCity { get; set; }
        public bool IsImportBlockedPostalCode { get; set; }
        public bool IsImportBlockedTitle { get; set; }
        public bool IsImportBlockedFloorSize { get; set; }
        public bool IsImportBlockedNumBedRooms { get; set; }
        public bool IsImportBlockedNumTotalBathRooms { get; set; }
        public bool IsImportBlockedNumEnsuite { get; set; }
        public bool IsImportBlockedNumKitchens { get; set; }
        public bool IsImportBlockedReceptionRooms { get; set; }
        public bool IsImportBlockedNumOfficeStudy { get; set; }
        public bool IsImportBlockedEntranceHall { get; set; }
        public bool IsImportBlockedParking { get; set; }
        public bool IsImportBlockedForSaleBy { get; set; }
        public bool IsImportBlockedForRentBy { get; set; }
        public bool IsImportBlockedIsFurnished { get; set; }
        public bool IsImportBlockedIsSmokingAllowed { get; set; }
        public bool IsImportBlockedPetFriendly { get; set; }
        public bool IsImportBlockedDescription { get; set; }
        public bool IsImportBlockedProvince { get; set; }
        public bool IsImportBlockedNeighborhood { get; set; }
        public bool IsImportBlockedHasPool { get; set; }
        public bool IsImportBlockedTemperatureControl { get; set; }
        public bool IsImportBlockedSecurityFeatures { get; set; }
        public bool IsImportBlockedNumGarages { get; set; }
        public bool IsImportBlockedHasGarden { get; set; }
        public bool IsImportBlockedPreferredGender { get; set; }
        public bool IsImportBlockedReferenceNumber { get; set; }
        public bool IsImportBlockedVideoURL { get; set; }
        public bool IsImportBlockedLongLat { get; set; }
        public bool IsImportBlockedLotSize { get; set; }
        public bool IsImportBlockedNumFloors { get; set; }
        public bool IsImportBlockedCurrency { get; set; }
        public bool IsImportBlockedCounty { get; set; }
        public bool IsImportBlockedAdditionalFeatures { get; set; }
        public bool IsImportBlockedImages { get; set; }
        public bool IsImportBlockedNumReceptionRooms { get; set; }
        public bool IsImportBlockedShowAddress { get; set; }
        public bool IsImportBlockedSchools { get; set; }
        public bool IsImportBlockedHospitals { get; set; }
        public bool IsImportBlockedRestaurants { get; set; }
        public bool IsImportBlockedVicinity { get; set; }
        public bool IsImportBlockedNumEntranceHall { get; set; }
    }
}
