//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int PropertyID { get; set; }
        public int AgencyID { get; set; }
        public int BranchID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int ListingType { get; set; }
        public string DwellingType { get; set; }
        public Nullable<int> ListingAgentID { get; set; }
        public Nullable<long> ListingPrice { get; set; }
        public Nullable<int> Levies { get; set; }
        public Nullable<int> RatesAndTaxes { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Title { get; set; }
        public Nullable<int> FloorSize { get; set; }
        public Nullable<byte> NumBedRooms { get; set; }
        public Nullable<byte> NumTotalBathRooms { get; set; }
        public Nullable<byte> NumEnsuite { get; set; }
        public Nullable<byte> NumKitchens { get; set; }
        public Nullable<byte> NumReceptionRooms { get; set; }
        public Nullable<byte> NumOfficeStudy { get; set; }
        public Nullable<byte> NumEntranceHall { get; set; }
        public string Parking { get; set; }
        public Nullable<System.DateTime> AvailabilityDate { get; set; }
        public string ForSaleBy { get; set; }
        public string ForRentBy { get; set; }
        public bool IsFurnished { get; set; }
        public bool IsSmokingAllowed { get; set; }
        public string PetFriendly { get; set; }
        public string ListingSettings { get; set; }
        public string Description { get; set; }
        public string Province { get; set; }
        public string Neighborhood { get; set; }
        public bool HasPool { get; set; }
        public string TemperatureControl { get; set; }
        public string SecurityFeatures { get; set; }
        public Nullable<byte> NumGarages { get; set; }
        public string ShareBasis { get; set; }
        public bool HasGarden { get; set; }
        public string PreferredGender { get; set; }
        public Nullable<System.DateTime> AvailableFrom { get; set; }
        public Nullable<System.DateTime> AvailableTo { get; set; }
        public Nullable<int> MinimumNights { get; set; }
        public Nullable<int> Sleeps { get; set; }
        public Nullable<int> SizeSQM { get; set; }
        public string ListingStatus { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string ReferenceNumber { get; set; }
        public string ExternalID { get; set; }
        public string VideoURL { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public Nullable<int> LotSize { get; set; }
        public Nullable<byte> NumFloors { get; set; }
        public string Currency { get; set; }
        public int SubListingType { get; set; }
        public string County { get; set; }
        public string ForSaleRent { get; set; }
        public string PriceType { get; set; }
        public Nullable<System.DateTime> DateLastImported { get; set; }
        public string AdditionalFeatures { get; set; }
        public string VacationLocationType { get; set; }
        public byte InventorySource { get; set; }
    }
}
