//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyDailyActivity
    {
        public int PropertyDailyActivityID { get; set; }
        public int PropertyID { get; set; }
        public int AgencyID { get; set; }
        public int PropertySubmitID { get; set; }
        public System.DateTime DateActivity { get; set; }
        public int Views { get; set; }
        public int PhoneClicks { get; set; }
        public int TotalViews { get; set; }
        public int TotalPhoneClicks { get; set; }
        public int NumLeads { get; set; }
        public int NumBumpUps { get; set; }
        public int NumTopAds { get; set; }
        public int NumHomepageGallery { get; set; }
        public int NumHighlights { get; set; }
        public int NumUrgent { get; set; }
        public int NumTopAds31 { get; set; }
        public int BranchID { get; set; }
    }
}
