//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignupRequest
    {
        public int SignupRequestID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string URL { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string RequestDetails { get; set; }
        public string EmailSentTo { get; set; }
        public string AlterContactPhone { get; set; }
        public string IPAddress { get; set; }
    }
}
