//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperAdminLog
    {
        public int SuperAdminLogID { get; set; }
        public int SuperAdminID { get; set; }
        public int UserID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}
