//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperAdmin
    {
        public int SuperAdminID { get; set; }
        public string Email { get; set; }
        public string HashedPassword { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte Culture { get; set; }
        public int GroupID { get; set; }
        public string SaltPassword { get; set; }
        public bool IsLocked { get; set; }
        public byte NumLoginAttemptFail { get; set; }
        public Nullable<System.DateTime> DateLocked { get; set; }
    }
}
