//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLog
    {
        public int TransactionLogID { get; set; }
        public byte TransactionLogType { get; set; }
        public double PaymentAmount { get; set; }
        public string PaymentCurrency { get; set; }
        public byte PaymentStatus { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DatePaid { get; set; }
        public string MAC { get; set; }
        public int AgencyID { get; set; }
        public int BranchID { get; set; }
        public string CustomerReference { get; set; }
        public string UniqueReference { get; set; }
        public int OverrideByID { get; set; }
        public int UserID { get; set; }
        public int SuperAdminID { get; set; }
        public string WorldPayStatus { get; set; }
        public string WorldPayReferenceId { get; set; }
    }
}
