//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginLog
    {
        public int UserLoginLogID { get; set; }
        public string Login { get; set; }
        public int UserID { get; set; }
        public bool IsSuccess { get; set; }
        public System.DateTime DateLogin { get; set; }
        public string RemoteIP { get; set; }
        public string Domain { get; set; }
        public Nullable<short> BrowserAgentID { get; set; }
        public string SSOToken { get; set; }
        public Nullable<System.DateTime> SSOTimestamp { get; set; }
    }
}
