//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public int AgencyID { get; set; }
        public int BranchID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string HashedPassword { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
        public Nullable<System.DateTime> DateSignedEULA { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string LeadContactEmail { get; set; }
        public bool IsActive { get; set; }
        public byte Culture { get; set; }
        public string UserType { get; set; }
        public short BumpUpCount { get; set; }
        public short TopAd7Count { get; set; }
        public short TopAd31Count { get; set; }
        public short HighlightCount { get; set; }
        public short UrgentCount { get; set; }
        public short HpgCount { get; set; }
        public bool RequirePasswordChange { get; set; }
        public short SrpGallery31Count { get; set; }
        public string UserNumber { get; set; }
        public string SaltPassword { get; set; }
        public bool IsShowVideo { get; set; }
        public bool IsLocked { get; set; }
        public byte NumLoginAttemptFail { get; set; }
        public Nullable<System.DateTime> DateLocked { get; set; }
        public int ReNewPackageID { get; set; }
        public bool IsShowBanners { get; set; }
    }
}
