//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VivanunciosLocations2016_09_19
    {
        public int VivanunciosLocationID { get; set; }
        public int LocationID { get; set; }
        public string LocationIDName { get; set; }
        public string Label { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public int ParentLocationID { get; set; }
    }
}
