//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VivanunciosPackage
    {
        public int VivanunciosPackageID { get; set; }
        public bool IsActive { get; set; }
        public string PackageName { get; set; }
        public string Description { get; set; }
        public string PackageType { get; set; }
        public short NumAds { get; set; }
        public short NumBumpUps { get; set; }
        public short NumTopAd7 { get; set; }
        public short NumTopAd31 { get; set; }
        public short NumHomepageGallery { get; set; }
        public short NumHighlights { get; set; }
        public short NumUrgent { get; set; }
        public int Price { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsHighlight { get; set; }
        public short NumSrpGallery31 { get; set; }
        public string GroupName { get; set; }
        public bool EnableAutoBumpUp { get; set; }
        public bool EnableCallTracking { get; set; }
        public byte AutoBumpUpPercent { get; set; }
    }
}
