//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begium.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorldPayNotificationLog
    {
        public int WorldPayNotificationLogID { get; set; }
        public string OrderCode { get; set; }
        public string OrderEvent { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Notification { get; set; }
    }
}
